name: Greetings

on:
  push:
    branches: [ "prod","prod-deploy" ]

env:
  OLIST: ${{ secrets.OLIST }}

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Message that will be displayed on users' first issue"
          pr-message: "Message that will be displayed on users' first pull request"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: test SSH
        run: ls; echo "${{ secrets.MY_SECRET }}"; echo "OK"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag olist:$(date +%j)

      - name: Transfer image
        run: docker save olist:$(date +%j) | wc

